### ISSUE TITLE
Meta : Z ording issues

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1016]
### Bug Description

Some games don't z-ordering correctly leading to seeing things you shouldn't
### Games Affect
- [ ] [007: From Russia with Love](https://xemu.app/titles/45410079/#007-From-Russia-with-Love) (Light source) #1009
- [x] [Breakdown]
- [x] [Catwoman]

- [x] [Far Cry Instincts]
- [x] [Knight's Apprentice: Memorick's Adventures](https://xemu.app/titles/4d490004/#Knight-s-Apprentice-Memorick-s-Adventures) (Amd and Intel) (Skybox) #655
- [x] [Juiced](https://xemu.app/titles/545100ef/#Juiced) (Objects)
![xemu-2022-06-02-20-32-23](https://user-images.githubusercontent.com/71127352/172956274-e6020db1-3892-4653-b627-d48ce17a2b94.png)
![xemu-2024-11-23-03-15-06](https://github.com/user-attachments/assets/b74edb99-6255-44ae-ac4b-f03b5d6a9da9)

- [x] [Marvel Nemesis: Rise of the Imperfects](https://xemu.app/titles/45410089/#Marvel-Nemesis-Rise-of-the-Imperfects)
![xemu-2022-08-09-20-02-49](https://user-images.githubusercontent.com/71127352/185688798-329dd5ad-26ea-4cf8-9e9c-682c3cf44a82.png)
- [x] [Miami Vice]
- [x] [Midtown Madness 3]
![xemu-2022-08-09-20-25-43](https://user-images.githubusercontent.com/71127352/195991580-97235388-a936-4a48-aa7a-918f380710bc.png)
- [x] [Peter Jackson's King Kong: The Official Game of the Movie](https://xemu.app/titles/5553004c/#Peter-Jackson-s-King-Kong-The-Official-Game-of-the-Movie) (Skybox)
![xemu-2022-06-02-19-00-54](https://user-images.githubusercontent.com/71127352/172956409-b355a6c9-de3a-4ea0-bf6a-aec65f1737a8.png)
- [x] [Project Gotham Racing]
![xemu-2022-08-19-20-08-40](https://user-images.githubusercontent.com/71127352/195360457-92f8aa5e-bae6-4abb-a26c-f9b371869f1d.png)
- [x] [Quantum Redshift](https://xemu.app/titles/4d530015/#Quantum-Redshift-Chou-Kousoku-Kuukan-Battle-Race)
- [x] https://xemu.app/titles/55530013/#Tom-Clancy-s-Rainbow-Six-3
- [x] https://xemu.app/titles/55530037/#Tom-Clancy-s-Rainbow-Six-3-Black-Arrow
- [x] [Tom Clancy's Splinter Cell](https://xemu.app/titles/5553000c/#Tom-Clancy-s-Splinter-Cell) (#804) (Objects)
- [x] [Splinter Cell Pandora Tomorrow](https://xemu.app/titles/55530019/#Tom-Clancy-s-Splinter-Cell-Pandora-Tomorrow) (#823)
- [x] [Tom Clancy's Ghost Recon: Advanced Warfighter](https://xemu.app/titles/55530054/#Tom-Clancy-s-Ghost-Recon-Advanced-Warfighter) (Objects)
- [x] [Syberia](https://xemu.app/titles/4d490006/#Syberia) #1134
- [x] [V-Rally 3](https://xemu.app/titles/49470034/#V-Rally-3) #887
![xemu-2023-10-22-17-38-18](https://github.com/xemu-project/xemu/assets/71127352/a6163d3e-021e-4403-b72d-52add14773d3)

### Expected Behavior

Should not be visible through objects

### xemu Version

Version: 0.7.25
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/7d6da227ba3b224647e35d2385419a3bec25a3b3
Date: Tue May 31 08:20:36 PM UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

### Additional Context

https://youtu.be/kRNOovUF354?t=206

**Comment by RageXbox** [comment]
Halo 2 has this as well

**Comment by cazzhmir** [comment]
[Splinter Cell Pandora Tomorrow](https://xemu.app/titles/55530019/#Tom-Clancy-s-Splinter-Cell-Pandora-Tomorrow) has the same behavior as its predecessor as well: #823

**Comment by MarcoLoves360** [comment]
farcry instincts aswell

**Comment by LeRutY** [comment]
Add Rainbow Six 3 and Rainbow Six Black Arrow to the list

**Comment by xDShot** [comment]
Any progress?

**Comment by svensvond** [comment]
Ghost Recon Advanced Warfighter - i see enemies through walls
0.7.85 - not fixed

**Comment by svensvond** [comment]
same here: #749

**Comment by Krathoon** [comment]
This will be a great boon whenever this is fixed.

**Comment by svensvond** [comment]
for sure .. anyone working on this?

**Comment by Amtemeri** [comment]
also happens in Metal Wolf Chaos

**Comment by svensvond** [comment]
so it affects still many many games, which make a larger bunch of them quit unplayable .. hmnm

**Comment by TGP482** [comment]
Splinter Cell 1 and Pandora Tomorrow can be removed since they're completely fixed

**Comment by mborgerson** [comment]
Can we get a test of the titles above? Some compatibility reports may need updating (e.g. https://xemu.app/titles/49470034/#V-Rally-3)

**Comment by Triticum0** [comment]
Someone need to test the tom clancy games will test them in time but might take few days to do so

**Comment by jyetcv** [comment]
Tom Clancy's Rainbow Six 3 is fixed:

![Image](https://github.com/user-attachments/assets/83f7b51a-f098-4934-844e-f691f4b3359b)

Tom Clancy's Rainbow Six 3: Black Arrow also fixed:

![Image](https://github.com/user-attachments/assets/c470bae7-8582-4a94-b19e-d4557e8b6918)

Tom Clancy's Ghost Recon: Advanced Warfighter looks fine:

![Image](https://github.com/user-attachments/assets/9612e504-ef7c-4328-8cb1-589a396fbf8f)

**Comment by Triticum0** [comment]
Thanks, only game need testing is Knight's Apprentice: Memorick's Adventures which I might just have to test on an old integrated Intel laptop. Might just move other issues to new pr as meta not relevant for only 2 games. Though matt can decide  what to do though i will closed once I make the new pr for remaining issues.

**Comment by Triticum0** [comment]
Also forgot Hobbit  need testing get round to in eventuality.

**Comment by jyetcv** [comment]
Peter Jackson's King Kong seems fine:

![Image](https://github.com/user-attachments/assets/66741ac5-77af-47b4-a780-ba51a35c32eb)

**Comment by Triticum0** [comment]
It not I've tested with latest build. It happens once he shots flare if your behind object. You can see light source

**Comment by jyetcv** [comment]
The flare being seen through the rock also occurs on real hardware. It is an issue with how the sprite is displayed.

**Comment by Triticum0** [comment]
So is issue fixed hw pic would be great. Thanks for all testing recently closed about 20 issues . You did a great job 👍

**Comment by jyetcv** [comment]
Thank you.

I think King Kong is fixed.
Here is a video of the flare recorded from an Xbox:

https://github.com/user-attachments/assets/43f884d1-2d0d-470d-80b5-4e30e4c2166c

**Comment by Triticum0** [comment]
I close this as meta not necessary anymore. other issues have there own pr and test them on Monday and where not fixed.
