### ISSUE TITLE
Meta : Z Fighting

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1020]
### Bug Description

Some Games experience z-fighting on object which does occur on hardware

 ### Games Affected
- [x] [Alias](https://xemu.app/titles/41430016/#Alias) (Video In the comments) Occurs on hardware https://youtu.be/7zg9VORgJsg?t=310
- [ ] [Aggressive Inline](https://xemu.app/titles/41430007/#Aggressive-Inline) (Video In the comments)
- [x] [Beyond Good & Evil](https://xemu.app/titles/55530018/#Beyond-Good-Evil) (Video In the comments) (Occurs on hardware)
- [ ] [Burnout 2](https://xemu.app/titles/41430019/#Burnout-2-Point-of-Impact) (#1161)
- [x] Carmen Sandiego: The Secret of the Stolen Drums (When picking up first puzzle piece) Occurs on hardware https://youtu.be/PpP_U4HxjLw?t=1182
- [ ] [Conker: Live & Reloaded](https://xemu.app/titles/4d530051/#Conker-Live-Reloaded) #575
- [x] https://xemu.app/titles/464c0002/#Crusty-Demons (Tree first mission)
- [ ] Ford vs Chevy
- [x] [Kao the Kangaroo: Round 2](https://xemu.app/titles/4a570003/#Kao-the-Kangaroo-Round-2) (Lighthouse Door)
![xemu-2022-08-06-00-47-58](https://user-images.githubusercontent.com/71127352/183224832-95b6df58-31ed-4296-8a73-5e392f793c07.png)
- [x] [King Arthur](https://xemu.app/titles/4b4e0024/#King-Arthur)(Rock on the first level has some Z fighting)
![xemu-2022-08-06-01-08-52](https://user-images.githubusercontent.com/71127352/183226197-039efc18-503c-4b04-b319-0004dff7a8be.png)

- 
- [ ] [NCAA Football 2005](https://xemu.app/titles/45410051/#NCAA-Football-2005)
- [ ] [NCAA Football 06](https://xemu.app/titles/45410080/#NCAA-Football-06)
- [ ] Outrun 2  (Video In the comments)
- [ ] Outrun 2 coast to coast
- [x] [Robin Hood: Defender of the Crown](https://xemu.app/titles/4343000c/#Robin-Hood-Defender-of-the-Crown) Occurs on hardware https://youtu.be/gaBWP_Scnmk?t=382
- [x] [SSX 3](https://xemu.app/titles/4541003c/#SSX-3)
- [x] [SSX Tricky](https://xemu.app/titles/45410004/#SSX-Tricky) 
- [x] [SSX On Tour](https://xemu.app/titles/45410082/#SSX-On-Tour)
- [x] [Sonic Heroes](https://xemu.app/titles/5345002b/#Sonic-Heroes) (Might be fixed) 

- [ ] [The Fairly OddParents: Breakin' Da Rules](https://xemu.app/titles/54510020/#The-Fairly-OddParents-Breakin-da-Rules) (#779)
- [ ] [Terminator 3: The Redemption](https://xemu.app/titles/4947003e/#Terminator-3-The-Redemption)

- [ ] [Spider Man 2](https://xemu.app/titles/4156002b/#Spider-Man-2) #575

### Expected Behavior

No z-fighting

### xemu Version

Version: 0.7.25
Branch: master
Commit: https://github.com/mborgerson/xemu/commit/7d6da227ba3b224647e35d2385419a3bec25a3b3
Date: Tue May 31 08:20:36 PM UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

### Additional Contexts
Any title which are fixed have been ticked and hyperlinked removed.
Edit 21/03/25: Retested Alias, Aggressive Inline, Beyond Good & Evil, Carmen Sandiego, NCAA Football 06, and Terminator 3: The Redemption have been tested and are still broken as of latest build ver 0.8.40

**Comment by Triticum0** [comment]
Aggressive Inline(Top corner on the hanger in the training level):

https://user-images.githubusercontent.com/71127352/183144974-fee9ec40-a763-431e-80f5-cdb066ad0163.mp4

Retested after v0.8.30 no change

**Comment by Triticum0** [comment]
Beyond Good & Evil

https://user-images.githubusercontent.com/71127352/183144998-d8ef8775-7955-4044-b414-da4191230129.mp4

Retested after v0.8.30 no change

[Renderdoc
](https://drive.google.com/file/d/1dIn47FPktQNYu4lPrfVGmIqxqkEfdfv3/view?usp=sharing)

**Comment by Triticum0** [comment]
Cabela's Deer Hunt 2004 Season

https://user-images.githubusercontent.com/71127352/175783579-57dddebb-a25d-42b8-9401-8b5b8d315962.mp4

**Comment by Triticum0** [comment]
Cabela's Deer Hunt 2004 Season

https://user-images.githubusercontent.com/71127352/175783579-57dddebb-a25d-42b8-9401-8b5b8d315962.mp4

**Comment by Triticum0** [comment]
Cars
https://user-images.githubusercontent.com/71127352/177056738-9345e54a-085e-4c33-8e75-3a3dc8f30d26.mp4

**Comment by AdadG** [comment]
Hey @Triticum0, could you please take Crash Bandicoot: The Wrath of Cortex off the list? The issue is solved:
At 1x:
![xemu exe Screenshot 2023 06 14 - 20 44 43 09](https://github.com/xemu-project/xemu/assets/81838886/074948fb-ff8d-424a-8e2d-e6cdf4ef67e5)
At 2x: 
![xemu exe Screenshot 2023 06 14 - 20 44 53 25](https://github.com/xemu-project/xemu/assets/81838886/682dc181-6475-4894-9329-ea9a80c83b0a)

**Comment by MasonT8198** [comment]
actually Incredible Hulk Ultimate Destruction no longer has this issue

**Comment by KreeseXD** [comment]
https://github.com/xemu-project/xemu/issues/2041 This also exists on Riddick

**Comment by Triticum0** [comment]
All the games left unticked properly needs retested, and properly will be fixed once Riddick gets fixed.

**Comment by superuser-does** [comment]
For avoidance of doubt:

Can I confirm that, when an affected game is ☑ticked, does that mean the issue has been corrected?

**Comment by Triticum0** [comment]
Yes, the issue does no occur. Not sure if I should just remove them but leave them  there until reports have been updated. As of 0.8.40 all ticked item have no z-fighting to my knowledge. tested most of them myself.

**Comment by superuser-does** [comment]
Thanks for clarifying @Triticum0.I think it is good to keep them visible in the interests of traceability.

It might just be good to clarify at the top that any title with that has been ticked can be considered "fixed" for the purposes of this Z-fighting issue.

**Comment by Triticum0** [comment]
Alias. Occurs on hardware(3 piliar in background)

https://github.com/user-attachments/assets/0e6f8016-1c98-4a26-b53e-341d19543c63

**Comment by Triticum0** [comment]
Outrun 2

https://github.com/user-attachments/assets/c573836c-f032-45ec-bd86-ba177f7447fa
