### ISSUE TITLE
WIP Meta : Games which suffer from laggy FMV's

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#1030]
### Bug Description

Some games suffer from hitching of fmv's of some kind which can cause issues like audio desync. This can be minor, like a missing frame or two every couple of seconds or constant in some cases making the game unplayable if the cutscenes are unskippable.
### Games Affected

- [x] [ 007: Agent Under Fire](https://xemu.app/titles/4541000d/#007-Agent-Under-Fire)
- [ ] [ 187 Ride or Die](https://xemu.app/titles/55530036/#187-Ride-or-Die)
- [x] 25 To Life
- [ ] 4x4 EVO 2
- [ ] 50 Cent: Bulletproof (Intro Rare)
- [x] Æon Flux
- [x] AFL Live 2003
- [ ] AFL Live Premiership Edition
- [ ] [Aliens Versus Predator: Extinction (Runs at 10 fps)](https://xemu.app/titles/56550022/#Aliens-Versus-Predator-Extinction)
- [ ] All-Star Baseball 2003
- [ ] All-Star Baseball 2004
- [ ] American Chopper
- [ ] AMF Bowling 2004
- [ ] Arctic Thunder
- [ ] Armed and Dangerous
- [ ] https://xemu.app/titles/4553000d/#Backyard-Wrestling-Don-t-Try-This-at-Home
- [ ] Bad Boys: Miami Takedown
- [ ] Bad Boys II
- [ ] Barbie Horse Adventures: Wild Horse Rescue
- [ ] BLACK 
- [ ] Break Nine: World Billiards Tournament
- [ ] Club Football
- [ ] Combat Elite: WWII Paratroopers
- [ ] CSI: Crime Scene Investigation (ubisoft logo)
- [ ] https://xemu.app/titles/4d530051/#Conker-Live-Reloaded
- [ ] https://xemu.app/titles/4d570022/#Gauntlet-Seven-Sorrows
- [ ] Gungriffon: Allied Strike
- [ ] Gotcha
- [ ] I-Ninja
- [ ] Jockey's Road
- [ ] https://xemu.app/titles/4a570003/#Kao-the-Kangaroo-Round-2
- [ ] https://xemu.app/titles/504c0002/#Kingdom-Under-Fire-The-Crusaders
- [ ] OutRun 2006: Coast 2 Coast (Backgrond FMV start menu)
- [ ] https://xemu.app/titles/41560018/#Pitfall-The-Lost-Expedition
- [ ] [Project Snowblind](https://xemu.app/titles/45530019/#Project-Snowblind)
- [ ] Predator: Concrete Jungle
- [ ] Red Ninja: End of Honor
- [ ] [Spawn-Armageddon](https://xemu.app/titles/4e4d000c/#Spawn-Armageddon)
- [ ] The Nightmare Before Christmas: Oogie's Revenge
- [ ] Torino 2006
- [ ] Urban Chaos: Riot Response
- [ ] Wreckless: The Yakuza Missions
- [ ] World War II Combat: Road to Berlin
- [ ] Wallace & Gromit: The Curse of the Were-Rabbit
- [ ] [XGRA: Extreme G Racing Association](https://xemu.app/titles/41430014/#XGRA-Extreme-G-Racing-Association)

### Expected Behavior

Should not lag

### xemu Version

Version: 0.7.28
Branch: master
Commit:https://github.com/mborgerson/xemu/commit/176b574403e0f4a08bfb1f8ab58e0f819a45cf81
Date: Fri Jun 3 21:40:57 UTC 2022

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 2600 Six-Core Processo
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 512.95

**Comment by RinMaru** [comment]
I-Ninja

**Comment by mysteria25** [comment]
BLACK also..

**Comment by abaire** [comment]
Hey @Triticum0 I spot checked Æon Flux and the intro video seems to play fine for me (with a release build with 0.7.58). Do you recall whether that was the video that skipped or if it was another one?

My system is older than yours:
CPU:          Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
OS Platform:  Linux
OS Version:   Ubuntu 21.10
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce GTX 1070/PCIe/SSE2
Driver:       4.0.0 NVIDIA 470.129.06
Shader:       4.00 NVIDIA via Cg compiler

I guess there could be a Windows vs. Linux component?

**Comment by caffeinekid** [comment]
Burnout 3 is terrible for this. Is there any progress on knowing what is going on with this problem?

**Comment by KhenemetHeru** [comment]
Battlestar Galactica as well, every cutscene after about 1 minute of playing, with evident spikes in the debug windows for every lag skip, just like the Futurama report here but constant. This has only gotten worse as updates are made over the last 3 years, so I have to assume it's not being worked on or low priority

**Comment by AzurikPerathia** [comment]
The European version of Azurik: Rise of Perathia also suffers from problem! On the other hand, the USA version doesn't!

https://cdn.discordapp.com/attachments/722155756622708744/1272976152927010816/LAG.mp4?ex=67d31b6d&is=67d1c9ed&hm=7ad89553863f590f73a389048bdb24a804d3e7c6b056cd12fbdf6985640afdd6&

**Comment by AzurikPerathia** [comment]
Can you add please #2022 too

**Comment by ArtemRU33** [comment]
Add star wars battlefront 2, laggy fmv even on the title scroll after a few minutes

**Comment by Bobble80** [comment]
You can add a few more games to the list that the intro FMV’s are stuttery and laggy in. 

Red Ninja: End of Honor
Predator: Concrete Jungle
Wreckless: The Yakuza Missions

**Comment by Bobble80** [comment]
Another one for the list is Superman Returns. The opening FMV is super choppy and laggy. And the in game audio is very crackly too. 

And this one I’m not sure if it counts or not, but I was testing the demo for Def Jam: Fight for NY and during the opening cutscene in the story mode, the audio goes out of sync. But it might be a different issue, due to the ongoing issue with the full game itself. 

And I noticed that the audio seemed to be also going out of sync in the opening cutscene of Final Fight: Streetwise.

**Comment by AidentheToyManiac** [comment]
The Nightmare Before Christmas: Oogie's Revenge also suffers from this issue, so that should be added to this list
