### ISSUE TITLE
texture color formats 0x17, 0x2c, 0x25, 0x31,0x3b are not implemented

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#320]
### Title Information
https://xemu.app/titles/4d570021/#Unreal-Championship-2-The-Liandri-Conflict - Crashes going to menu
https://xemu.app/titles/54510008/#MotoGP - Second intro crashes
https://xemu.app/titles/4d57000b/#NHL-Hitz-2003 - Crashes before boot
*https://xemu.app/titles/4d570012/#FireBlade - When going in-game
https://xemu.app/titles/534300fb/#Just-Cause - When going in-game
https://xemu.app/titles/4d53006b/#MechAssault-2-Lone-Wolf - After intro
*https://xemu.app/titles/45530016/#Backyard-Wrestling-2-There-Goes-the-Neighborhood - When going in-game
*https://xemu.app/titles/4553000d/#Backyard-Wrestling-Don-t-Try-This-at-Home - Menu
### Bug Description
These Unimplemented texture color formats cause the emulator to hit an assertion.

- [x] 0x17 (MechAssault 2: Lone Wolf)(fixed via #401)
- [x] 0x2c (Just Cause)(fixed via #407)
- [x] 0x25 (MotoGP and NHL Hitz 2003)(fixed via #404 )
- [x] 0x31 (FireBlade, Backyard Wrestling: Don't Try This at Home, Backyard Wrestling 2: There Goes the Neighborhood) (fixed via #27) 
- [x] 0x3b (Unreal Championship 2: The Liandri Conflict) (fixed via #395)
### Expected Behavior 
For the games to make it in-game.

### Version
<ul>
<li>Version: build-202106020756( <a href="https://github.com/mborgerson/xemu/commit/3884b8d44b4bfaed73f26227cd88d7946e2dfaa5"><tt>3884b8d</tt></a>)</li>
<li>Last-known Working: Unknown</li>
</ul>
<h3>System Information</h3>

Field | Value
-- | --
OS | Windows 10 64-bit (21H1)
CPU | AMD Ryzen 5 2600 Six-Core Processor @ 3.40GHz
Graphics Device | AMD Radeon RX 5700 XT
Graphics Driver | 4.0.148202 Core Profile Context 21.3.2 27.20.15003.5017

### Additional Context

Big thanks to Ernegien for implementing most of the missing textures

**Comment by Triticum0** [comment]
All the textures which cause assertions are now implemented. But I'm not sure if they're more work to be done on the texture formats?

**Comment by GXTX** [comment]
Should still be an open issue. One of the last requested is still open as PR and not merged.
