### ISSUE TITLE
Broken games catgory megathread.

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#328]
I've decided to create a tracking issue for all the broken gaming listed on the compact list

- [x] Antz Extreme Racing #322
- [x] Beyond Good & Evil #323
- [x] Blade II #324
- [x] Braveknight: Leverant Eiyuuden  #322
- [x] College Hoops 2K6 #317
- [x] College Hoops 2K7 #317
- [x] Cricket 2005 #313
- [x] Def Jam: Fight for NY #313
- [x] ESPN College Hoops 2K5 #317
- [x] ESPN NBA 2K5 #317
- [x] ESPN NFL 2K5 #317
- [ ] ESPN NFL Football #326
- [x] ESPN NFL PrimeTime 2002  #60 and #322
- [x] ESPN NHL 2K5 #317
- [ ] F1 2002 #325
- [x] FIFA Football/Soccer 2004 #313
- [x] FIFA Football/Soccer 2005 #313 
- [x] Galleon
- [x] Group S Challenge #60 
- [x] Juiced #841
- [x] Largo Winch: Empire Under Threat #322
- [x] MX vs. ATV Unleashed #323
- [x] Major League Baseball 2K5 #317
- [x] Major League Baseball 2K5: World Series Edition #317
- [x] Major League Baseball 2K6 #317
- [x] Major League Baseball 2K7 #317
- [x] Malice #322
- [x] Metal Dungeon #322
- [x] MotoGP #320
- [x] NBA 2K6 #317
- [x] NBA 2K7 #317
- [x] NHL 2K6 #317
- [x] NHL 2K7 #317
- [x] NBA Live 2003 #313
- [x] NBA Live 2004 #313
- [x] NCAA March Madness 2004 #313
- [ ] NFL Fever 2004 #797
- [x] NHL Hitz 2003 #320
- [x] Need for Speed: Most Wanted  #309
- [x] Need for Speed: Underground 2  #309
- [x] OutRun 2006: Coast 2 Coast  #309
- [x] Outlaw Golf: 9 More Holes of X-Mas (There's a problem with the disc using. It may be dirty or damaged) 
- [x] Pirates of the Caribbean #312 Not sure about this someone would need to verify.
- [ ] Pro Fishing Challenge #108
- [x] Project: Snowblind #321
- [x] RoboCop #322
- [x] Rugby 06 #313
- [x] Rugby 2005 #313
- [x] Shikigami no Shiro Evolution #312 Not sure about this someone would need to verify.
- [x] Steel Battalion #60
- [x] The Wild Rings Segmentation fault need more testing (crash no assertion) #360
- [x] Tiger Woods PGA Tour 06 Segmentation fault need more testing (crash no assertion only on windows) #360
- [x] Tiger Woods PGA Tour 2004 Segmentation fault need more testing (crash no assertion only on windows) #360
- [x] UEFA Euro 2004: Portugal #313
- [ ] WWE WrestleMania 21 #559
- [x] Whiplash #321

**Comment by Triticum0** [comment]
All segmentation Faults on linux have been fixed there are only known assertion that need to be fixed issue

**Comment by Triticum0** [comment]
Only 5 game left in broken =)

**Comment by simi** [comment]
:-o I see 7.

**Comment by Triticum0** [comment]
When Largo Winch: Empire Under Threat and  ESPN NFL PrimeTime 2002 are retested it will be 5

**Comment by Triticum0** [comment]
I think this has served its purpose

**Comment by empireromain** [comment]
Hello, f1 2002 is now in the start category ( 29/10/2022) :)
