### ISSUE TITLE
 Games which have currently unexplainable crashes

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#376]
I've decided to create a tracking issue for all gaming with having no log or freeze when crashing which are listed on the compact list. This might be 100% accurate due to some people not posting the log to the compact report.

### Crashes no assertion
- [x] AND 1 Streetball
- [x] American McGee Presents Scrapland(Regression)(https://www.youtube.com/watch?v=JpRT7-2pDHo)
- [x] Blinx 2: Masters of Time and Space 
- [x] Brute Force
- [x] Chessmaster
- [x] Chicago Enforcer (Regression from XQEMU *3)
- [x] Conan (Windows only) #153 
- [x] Crusty Demons*1 (Regression from XQEMU)
- [x] Curse: The Eye of Isis (Crashes ingame randomly Possible regression)
- [x] Dreamfall: The Longest Journey (Malloc issue)
- [x] Eggo Mania*2 (Regression from XQEMU)
- [x] Fahrenheit 
- [x] Gauntlet: Seven Sorrows (Windows only)
- [ ] Gotcha!
- [x] Inside Pitch 2003 (segmention fault/Intel only)
- [ ] Jade Empire (Bonus Disc)
- [x] Kingdom Under Fire: The Crusaders(Windows only)
- [x] Lemony Snicket's A Series of Unfortunate Events (Regression from XQEMU) (It Fixed or is window/amd only)
- [x] Manhunt
- [x] Mashed: Drive to Survive (Windows only)
- [x] MLB SlugFest 2006
- [x] Peter Jackson's King Kong: The Official Game of the Movie
- [x] Phantasy Star Online Episode  I & II(Need retesting)
- [x] Project Gotham Racing 2(Regression discussed in #384)
- [x] Project Zero II: Crimson Butterfly: Director's Cut
- [x] Return to Castle Wolfenstein: Tides of War (Intro hang)
- [x] Terminator 3: Rise of the Machines (Windows only)
- [x] The Terminator: Dawn of Fate
- [x] The Wild Rings (Windows only)
- [x] Tiger Woods PGA Tour 2004 (Legend Tour match FMV)
- [x] Tiger Woods PGA Tour 06 (Windows only)
- [x] Tiger Woods PGA Tour 07

### Freezes
- [ ] Brothers in Arms: Earned in Blood #583 
- [ ] Brothers in Arms: Road to Hill 30 #583 
- [x] Def Jam: Fight for NY (Infinite loading)(This aslo affect mircosoft offical fusion emulator so it probably game specific)
- [x]  Double-S.T.E.A.L (Regression)
- [x]  DreamWorks Over the Hedge (on FMV's)
- [ ] [FIFA 07](https://xemu.app/titles/454100a6/) (Before going in-game)
- [x] Gladius (Regression from XQEMU)
- [x] Gungriffon: Allied Strike (Regression from XQEMU *4)
- [x] Kikou Heidan J-Phoenix + (drops under 1fps)
- [x] Outlaw Golf (drops under 1fps)
- [x] Outlaw Golf: 9 More Holes of X-Mas (drops under 1fps)
- [ ] Total Immersion Racing (Regression from after the 6 july or NTSC exclusive or bad dump?)
- [x] Ultra Bust-A-Move (drops under 1fps)

### Additional Context
This is for documentation purposes mainly and most of the information was taken for old xqemu compatibly spreadsheet.
References 
*1 https://www.youtube.com/watch?v=QoMt6d4xdDk
*2 https://docs.google.com/spreadsheets/d/1sVtQ9SNPathKAMCqfYtvJQP0bs0UeLzP9otPHvZDMwE/htmlview#gid=709879345
*3 https://www.youtube.com/watch?v=89IHdhk8skc
*4 https://www.youtube.com/watch?v=KCQFsglwTTo

**Comment by MaouYumisu1** [comment]
Tiger Woods PGA Tour 2004 Crashes with no assertion when you mash start or A during Intro FMV's or after you select a Legend Tour match and mash to skip FMVs.
https://youtu.be/fjcWEReM1QA
https://youtu.be/OXEC9zHtKJU

**Comment by WitchfinderMH** [comment]
Manhunt is not crashing anymore on latest builds.

**Comment by nolrinale** [comment]
Phantasy Star Online Episode I & II is not crashing, just extremelly slow.

**Comment by Joshhmarshh** [comment]
Mad Dash Racing freezes completely within 5-10 seconds of gameplay. Have not been able to find a fix yet

**Comment by builder-main** [comment]
Can confirm that gladius (FR) crashes on first loading screen (xemu 0.8.94)
