### ISSUE TITLE
 Intro games catgory megathread

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#560]
I've decided to create a tracking issue for all the Intro gaming listed on the compact list.

- [x] AND 1 Streetball  #535 
- [x] America's Army: Rise of a Soldier  #368 
- [x] American Chopper 2: Full Throttle #309
- [x] American McGee Presents Scrapland #535 ~~Need retesting on windows~~ Works on linux and windows
- [x] ATV: Quad Power Racing 2 #322
- [x] Backyard Wrestling 2: There Goes the Neighborhood (Need to be added to the website) #60
- [x] Backyard Wrestling: Don't Try This at Home (Need to be added to the website) #60 and #383
- [x] Batman: Rise of Sin Tzu #635 ~~Needs retesting~~
- [x] Blade II #324
- [x] Breakdown #329
- [ ] Brothers in Arms: Earned in Blood #309, #376 and #583
- [ ] Brothers in Arms: Road to Hill #309, #376 and #583
- [x] Carve #367
- [x] Championship Bowling #331
- [x] College Hoops 2K6 #329
- [x] College Hoops 2K7 #329
- [x] Constantine #161
- [x] Crime Life: Gang Wars  #375
- [ ] Curious Geoge  #537
- [x] Dance Dance Revolution Ultramix #60
- [ ] Def Jam: Fight for NY #376
- [x] Die Hard: Vendetta #324
- [ ] Double-S.T.E.A.L #376
- [x] Dr. Muto #324
- [x] DreamWorks Madagascar (Need to be added to the website) #387
- [ ] DreamWorks Over the Hedge #376
- [x] ESPN College Hoops 2K5 #329
- [x] ESPN NBA 2K5 #329
- [x] ESPN NBA Basketball #329
- [x] ESPN NFL 2K5 #329
- [x] ESPN NHL 2K5 #329
- [x] FIFA 07 (Need retesting) working [here](https://www.youtube.com/watch?v=mgSVZcs3Fmg) #376
- [x] FireBlade #60 
- [ ] FlatOut (Linux/NTSC) #559
- [ ] FlatOut 2 (Linux/NTSC)  #559
- [x] Ford Racing 2 #315
- [x] Full Spectrum Warrior: Ten Hammers #288
- [ ] Group S Challenge #379 
- [ ] Guilty Gear X2 #Reload: The Midnight Carnival #330
- [x] Heroes of the Pacific #530
- [x] Inside Pitch 2003 #60
- [ ] Jade Empire (Bonus Disc) #376
- [x] Karaoke Revolution #309
- [x] Karaoke Revolution Party #309
- [x] Kingdom Under Fire: The Crusaders #535 (~~Needs retesting~~)
- [x] Lakemasters: Bass Fishing Game #161
- [x] Legends of Wrestling #60 
- [x] Legends of Wrestling II #60
- [x] Links 2004  #375
- [x] Major League Baseball 2K5 #329
- [x] Major League Baseball 2K5: World Series Edition #329
- [x] Major League Baseball 2K6 #329
- [x] Major League Baseball 2K7 #329
- [x] Marvel Nemesis: Rise of the Imperfects #385
- [ ] MechAssault 2:Lone Wolf #376
- [x] Metal Arms: Glitch in the System  #116 and #373
- [x] Midnight Club 3: DUB Edition  #116
- [x] Midway Arcade Treasures #330
- [x] Mortal Kombat: Shaolin Monks #60
- [ ] Mortal Kombat: Shaolin Monks (The Suffering 2 demo)
- [x] MotoGP: Ultimate Racing Technology 3  #375
- [x] MTX-Mototrax (Needs Restesting) #564
- [ ] N.U.D.E.@: Natural Ultimate Digital Experiment (Need retesting with prefericals )
- [x] NBA 2K6 #329
- [x] NBA 2K7 #329
- [x] NBA Jam #670
- [x] Need for Speed: Carbon #309
- [ ] NHL 2002 #315
- [x] NHL 2K6 #329
- [x] NHL 2K7 #329
- [ ] NHL Rivals 2004 #536
- [x] Nickelodeon Avatar: The Last Airbender #364
- [x] Operation Flashpoint: Elite #535
- [ ] Outlaw Golf #376
- [ ] Outlaw Golf: 9 More Holes of X-Mas #376
- [x] Phantasy Star Online Episode I & II(Regression) #376 (Needs retesting Works on M1)
- [x] Phantom Dust #54
- [x] Playboy: The Mansion #116 
- [x] Project Gotham Racing 2
- [x] Project Zero #309 
- [x] Project Zero II: Crimson Butterfly: Director's Cut #549
- [x] R:Racing #329
- [x] Rally Fusion: Race of Champions #322
- [ ] Real World Golf (Need retesting using Gametrak)
- [x] Reign of Fire #60
- [x] Robotech: Invasion  #537
- [x] Rogue Ops #324
- [x] Rolling  #535
- [x] Room Zoom: Race for Impact #567 
- [ ] RPM Tuning  #332
- [x] SeaBlade #547
- [x] Sentou Yousei Yukikaze: Yousei no Mau Sora #330
- [x] Serious sam (Should be in Start)
- [x] Showdown: Legends of Wrestling #60
- [x] Spikeout-BattleStreet #60
- [x] Spy vs. Spy  #537
- [x] SSX 3 #520
- [x] SSX On Tour #366
- [x] Star Wars: Obi-Wan #566 
- [x] Star Wars: The Clone Wars + Tetris Worlds
- [x] Sudeki #161 (Needs Restesting)
- [x] The Italian Job #322
- [x] The Wild Rings (Needs Restesting) #60
- [ ] Top Gear: RPM Tuning  #332
- [x] Torino 2006  #375
- [x] Total Immersion Racing #161 (Needs Restesting)
- [x] Touge R #322 
- [x] TransWorld Snowboarding  #491 and #322
- [x] Ultimate Beach Soccer  #375
- [ ] Ultra Bust-A-Move  #376
- [x] Van Helsing  #405
- [x] World War II Combat: Iwo Jima  #334

**Comment by Spidy123222** [comment]
For metal arms: glitch in the system. The hard-scale branch so far fixed it so will have to see once it merges to master but for now this is one of the issues that are reported on metal arms: glitch in the system.

[Issue #373](https://github.com/mborgerson/xemu/issues/373)

**Comment by Triticum0** [comment]
Edit: it's 111 and not 107 because of Spikeout-BattleStreet and Sentou Yousei Yukikikaze: Yukikaze: Yousei no Mau Sora are incorrectly reported. Also there a demo Mortal Kombat: Shaolin Monks (The Suffering 2 demo) and Flatout is only is an intro game in my testing.

**Comment by simi** [comment]
I have requested status update for OFP:E (https://github.com/mborgerson/xemu/issues/406#issuecomment-968181518) since it is playable now without problems, but since I'm still banned on Discord (for misunderstanding, and even I tried to explain stuff over email) I can't do update on my own.

**Comment by Triticum0** [comment]
@simi I'm happy to write a report for OFP:E as i have the game, but when testing it seemed like a overlay was misaligned making the image blurry. Was there anything other bug present when you were testing the game. So I included it into the report.
Also did you complete the game when testing.

**Comment by simi** [comment]
@Triticum0 can you post a screenshot and mark the problems in there?

**Comment by Triticum0** [comment]
@simi Post the problem were on the report or Github. It only appears In cut-scenes. John god game did a video of the game if you don't know what I'm talking about: https://youtu.be/x9BsUlUfI1o?t=157. And you didn't tell me how far you got in the game. The computer I used for testing can't run the game at full speed, so I only finished the tutorial. Also not sure if it is the custom build he using, but john gameplays only at 20 fps cap, which I don't think should be capped too.

**Comment by MarcoLoves360** [comment]
midnight club 3 throw me lots of asserts and if i spam ignore eventually crashes on type name screen. tested on latest master.

Breakdown gets stuck on infinite loading

nfs carbon throws assert as soon as you boot the game.

pgr 2 regression is fixed

**Comment by Triticum0** [comment]
@MarcoLoves360 What the assertion for carbon, it's properly #520. If so, I'll add it to the list. Other's fixed by fix/arrays, so not worth testing on-till it merged. But thank you for the info.

**Comment by mborgerson** [comment]
@Triticum0 Has you tested the titles with checkmarks? If you have verified the game is now fixed, please update the game status in the compatibility tracker or ask other testers to help update it, then remove the game from this list

**Comment by MarcoLoves360** [comment]
> @MarcoLoves360 What the assertion for carbon, it's properly #520. If so, I'll add it to the list. Other's fixed by fix/arrays, so not worth testing on-till it merged. But thank you for the info.

yes carbon goes in game

**Comment by Triticum0** [comment]
@mborgerson This is mostly updated for you to easily find known game blockers as I find using Compatibility reports cumbersome to use and is not always up-to-date as some games are forgotten to be retested after the issue has been closed. Most of them have been tested by john god games, my and guru emulation, but John doesn't write a report for the games he tested recently, so some report stays out of date.

Here is a list of fixed games I checked and where or not there been tested
Games | Tested by | Updated on Compatibility report
-- | -- | --
AND 1 Streetball | Tritcum0 | Y
American McGee Presents Scrapland | Tritcum0 | Y
Backyard Wrestling: Don't Try This at Home | [John GodGames](https://www.youtube.com/watch?v=aeuQ7GPT1w4) | N
Backyard Wrestling 2: There Goes the Neighborhood | [John GodGames](https://www.youtube.com/watch?v=GIvYs4yq4fg) | N
Constantine | Tritcum0 | Y
Dance Dance Revolution Ultramix | Tritcum0 | Y
FireBlade | [John GodGames](https://www.youtube.com/watch?v=Gnbqg_d0LwE) | N
Inside Pitch 2003 | Tritcum0 | Y
Kingdom Under Fire: The Crusaders | Tritcum0 | Y
Lakemasters: Bass Fishing Game | Tritcum0 | Y
Legends of Wrestling | [John GodGames](https://www.youtube.com/watch?v=qV47EYYdqpw) | N
Legends of Wrestling 2 | [John GodGames ](https://www.youtube.com/watch?v=2QEy1bH8w3o) | N
Mortal Kombat: Shaolin Monks | turbohao | N
Operation Flashpoint: Elite | Tritcum0 | Y
Reign of Fire | [John GodGames ](https://www.youtube.com/watch?v=JPa0KbTUFfk) | N
Rolling | Tritcum0 | Y
Showdown: Legends of Wrestling | N/A | N
Spikeout BattleStreet | Tritcum0 | Y
Sudeki | Tritcum0 | Y
The Wild Rings | Tritcum0 | Y
Total Immersion Racing | [John GodGames*](https://www.youtube.com/watch?v=IcdaaeCvev8) | N

*= Was on a custom build before it was merged.

**Comment by MarcoLoves360** [comment]
America's Army: Rise of a Soldier - Works

American Chopper 2: Full Throttle - N (throws assert window)

Batman: Rise of Sin Tzu - N (throws assert window after loading mission)

Blade II - Works

Breakdown - N (throws assert window loading mission)

Brothers in Arms: Earned in Blood - Works (goes in-game but black screen hud and menu overlaps)

Brothers in Arms: Road to Hill - N (cant get it to even boot)

Crime Life: Gang Wars  - N (crashes after loading mission)

Fifa 07 - N (stuck on loading match)

Ford Racing 2 - N (throw assert on loading)

Full Spectrum Warrior: Ten Hammers - Works?? (assert window shows after press ignore once goes in-game)

Nickelodeon Avatar: The Last Airbender - N (throws assert after loading screen)

Playboy: The Mansion - Works?? (have to spam ignore on assert window lots of times to go in-game)

Project Zero - Works (goes in-game but hard to navigate because black menu)

Project Zero 2 - N (crashes on loading)

Rogue Ops  - Works

Serious Sam - Works

Spy vs Spy - N (throws assert window)

Star Wars: Obi-Wan - N (crashes after loading)

Van Helsing - Works?? (have to spam ignore on assert window)

**Comment by Triticum0** [comment]
@MarcoLoves360 What The assertion for Spy vs Spy Would be useful to know. Also is Serious Sam graphical glitches still present(Enemy thought wall, broken sky box)

**Comment by Triticum0** [comment]
g   |       
-- | -- 
    |       
Also this is how I made table so your comment more readable

**Comment by MarcoLoves360** [comment]
![image](https://user-images.githubusercontent.com/30830822/148700611-74dad2dc-78f0-4f16-8b74-c4ba2e39f9f6.png)

Thats the message i get.
Yes serious sam still has graphical glitches you can see through walls.

**Comment by MarcoLoves360** [comment]
playboy the mansion is now working fine

**Comment by Triticum0** [comment]
Closing not useful anymore use the Compatibility report
