### ISSUE TITLE
Meta: Audio Issues 

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#904]
### Bug Description

Games that have problems with Audio Will be placed here to avoid making duplicate issues.
### Audio Looping *
- [x] https://xemu.app/titles/55530056/#AND-1-Streetbal
- [x] https://xemu.app/titles/4d570002/#Arctic-Thunder (During Intro)
- [ ] https://xemu.app/titles/45410083/#Black
- [ ] https://xemu.app/titles/41560051/#Call-of-Duty-2-Big-Red-One
- [ ] https://xemu.app/titles/4b4e0008/#International-Superstar-Soccer-2
- [x] https://xemu.app/titles/4d530008/#Night-Caster-Defeat-the-Darkness
- [x] https://xemu.app/titles/4a410002/#Night-Caster-II-Equinox
- [ ] https://xemu.app/titles/4a570002/#Neighbours-from-Hell #531
- [x] https://xemu.app/titles/544d0006/#Outlaw-Golf #579
- [x] https://xemu.app/titles/5655001b/#Outlaw-Golf-9-Holes-of-X-Mas
- [x] https://xemu.app/titles/434d0008/#Prisoner-of-War
- [x] https://xemu.app/titles/4947003b/#Terminator-3-Rise-of-the-Machines
- [x] https://xemu.app/titles/4d4a000c/#Ultra-Bust-A-Move #579 and #822
- [x] https://xemu.app/titles/4947003c/#Unreal-II-The-Awakening

### Audio Buzzing/Hissing audio channels

- [ ] https://xemu.app/titles/45410074/#Cricket-2005
- [x] Die Hard Vendetta (Hissing)
- [ ] https://xemu.app/titles/45410017/#FIFA-Soccer-2003
- [x] https://xemu.app/titles/4541003b/#FIFA-Football-2004
- [ ] https://xemu.app/titles/4541004e/#FIFA-Soccer-2005
- [ ] https://xemu.app/titles/45410078/#FIFA-Soccer-06
- [ ] https://xemu.app/titles/454100a6/#FIFA-07
- [ ] https://xemu.app/titles/4541009c/#FIFA-World-Cup-Germany-2006
- [ ] http://xemu.app/titles/45410045/#MVP-Baseball-2004
- [ ] https://xemu.app/titles/45410061/#Rugby-2005
- [ ] https://xemu.app/titles/45410087/#Rugby-06

###  sample rate Issues

- [ ] https://xemu.app/titles/54540019/#Manhunt (On sound affects) 
- [ ] https://xemu.app/titles/4d530021/#Crimson-Skies-High-Road-to-Revenge

### Incorrect Audio Mixing *

- [x] Auto Modellista
- [x] Armed and Dangerous (Cutscenes voice audio only plays thought one ear)
- [x] Bass Pro Shops Trophy Bass 2007 popping
- [x] Beat Down (Foot steps are too loud)
- [x] Crash Nitro Kartmostly 
- [x] Crash Twinsanity (Sounds are also play at full volume regardless of how far they are from the player)
- [x] Crash Tag Team Racing
- [x] Doom 3
- [x] Doom 3 Resurrection of Evil
- [x] Delta Force Black Hawk Down
- [ ] https://xemu.app/titles/4d570012/#FireBlade
- [ ] http://xemu.app/titles/4d530053/#Grabbed-by-the-Ghoulies (sound effects are very low volume)
- [x] Gungriffon Allied Strike (To Loud)
- [x] IndyCar Series 2005
- [ ] https://xemu.app/titles/504c0006/#Kingdom-Under-Fire-Heroes (Untested)
- [x] Land of the Dead Road to Fiddler's Green
- [x] NFL Fever 2002 (Tackle are to loud, announcers and music to queit)
- [x] Nickelodeon SpongeBob SquarePants Lights Camera Pants
- [x] Nickelodeon Tak 2 The Staff of Dreams ( very low quality the grunts and voice)
- [x] https://xemu.app/titles/4d530028/#NFL-Fever-2003 (Tackle are to loud)
- [ ] https://xemu.app/titles/4d530008/#Night-Caster-Defeat-the-Darkness (Tested but has other issues make in ambiguous)
- [ ] https://xemu.app/titles/4a410002/#Night-Caster-II-Equinox (Tested but has other issues make in ambiguous)
- [x] Mace-Griffin-Bounty-Hunter (Sound effect are too Loud)
- [x] Men-of-Valor (Gun fire too loud)
- [x] MotoGP (Engine too Loud)
- [ ] https://xemu.app/titles/58490005/#Motor-Trend-Presents-Lotus-Challenge (Crackle)
- [x] Panzer-Dragoon-Orta (Gun fire to loud)
- [x] Painkiller-Hell-Wars (Sound effects are too low)
- [x] Quantum-Redshift-Chou-Kousoku-Kuukan-Battle-Race
- [x] RalliSport-Challenge-2 (#639)
- [ ] https://xemu.app/titles/424d0002/#Reign-of-Fire (Engine too Loud)
- [x] Rolling
- [x] Sonic-Riders
- [x] Superman-The-Man-of-Steel
- [x] Street-Fighter-Anniversary-Collection
- [x] The-Elder-Scrolls-III-Morrowind
- [x] The-Incredible-Hulk-Ultimate-Destruction(Intro FMV)
- [x] TimeSplitters-2 (music quiet)
- [ ] https://xemu.app/titles/41560049/#Tony-Hawk-s-American-Wasteland (Skateboard sound)
- [x] Voodoo-Vince (left channel has most of the voices )

### Missing Audio Effects/Cuts Out
- [x] https://xemu.app/titles/45530018/#25-to-Life (Cut Out)
- [ ] https://xemu.app/titles/55530057/#Blazing-Angels-Squadrons-of-WWII(Intro Music)
- [ ] https://xemu.app/titles/41530001/#Break-Nine-World-Billiards-Tournament
- [x] https://xemu.app/titles/58490004/#Black-Stone-Magic-Steel (Cuts Out)
- [ ] https://xemu.app/titles/4d53001e/#Brute-Force (Cutscenes Audio Cuts Out)
- [ ] https://xemu.app/titles/43430008/#Capcom-vs-SNK-2-EO (Both) (#526)
- [x] Dr-Seuss-The-Cat-in-the-Hat (Missing)
- [x] Harry-Potter-and-the-Chamber-of-Secrets (Both)
- [x] Halo-Combat-Evolved (#143)
- [ ] https://xemu.app/titles/564e0004/#Hunter-The-Reckoning (#595)
- [ ] https://xemu.app/titles/5655002d/#Hunter-The-Reckoning-Redeemer (#595)
- [x] Goblin-Commander-Unleash-the-Horde (Missing)
- [ ] https://xemu.app/titles/43430007/#Marvel-vs-Capcom-2-New-Age-of-Heroes (Missing Sound effect)
- [x] https://xemu.app/titles/54510005/#Red-Faction-II (Audio missing except music)
- [x]  Sudeki (Menus)
- [x] Total-Club-Manager-2005
- [x] https://xemu.app/titles/4947003b/#Terminator-3-Rise-of-the-Machines (Cuts Out)
- [ ] https://xemu.app/titles/45410091/#Half-Life-2

### Max Utilziation crackiling/Stuttering
- [x] 007-Agent-Under-Fire
- [x] 2002-FIFA-World-Cup
- [ ] https://xemu.app/titles/54540010/#Carve
- [x] https://xemu.app/titles/52410006/#Crash
- [x] https://xemu.app/titles/42560002/#Disney-s-Chicken-Little
- [x] https://xemu.app/titles/4541002c/#Dead-to-Rights
- [x] https://xemu.app/titles/53450026/#ESPN-NHL-Hockey
- [ ] https://xemu.app/titles/4541003b/#FIFA-Football-2004
- [ ] https://xemu.app/titles/45410072/#FIFA-Street
- [x] https://xemu.app/titles/45410085/#FIFA-Street-2
- [ ] https://xemu.app/titles/45410086/#Fight-Night-Round-3*
- [x] https://xemu.app/titles/4d530064/#Halo-2 (mixing)
- [ ] https://xemu.app/titles/4541001d/#NCAA-Football-2003*
- [ ] https://xemu.app/titles/45410044/#NCAA-March-Madness-2004
- [x] http://xemu.app/titles/45410050/#NBA-Live-2005
- [x] https://xemu.app/titles/4d530011/#NBA-Inside-Drive-2002(Pause menu)
- [ ] https://xemu.app/titles/45410002/#NASCAR-Thunder-2002
- [ ] https://xemu.app/titles/4541001b/#NASCAR-Thunder-2003
- [ ] https://xemu.app/titles/45410048/#NFL-Street
- [ ] https://xemu.app/titles/45410057/#NFL-Street-2
- [ ] http://xemu.app/titles/454100a5/#NHL-07 (weird static/Crackling/Pops)
- [ ] http://xemu.app/titles/4541007c/#NHL-06 (weird static/Crackling/Pops)
- [x] OutRun 2006 Coast 2 Coast (Stuttering)
- [x] https://xemu.app/titles/4d530015/#Quantum-Redshift-Chou-Kousoku-Kuukan-Battle-Race* (Only occurs  with RT DSP on)
- [ ] https://xemu.app/titles/49470015/#Racing-Evoluzione
- [ ] https://xemu.app/titles/544d0009/#SeaBlade (Menus, weird static/Crackling/Pops)
- [x] Starsky-Hutch
- [x] https://xemu.app/titles/454d0022/#Taito-Legends-2
- [ ] https://xemu.app/titles/434d0050/#TOCA-Race-Driver-3
- [x] Totaled
- [ ] https://xemu.app/titles/45410021/#Tiger-Woods-PGA-Tour-2003
- [ ] https://xemu.app/titles/45530011/#Whiplash
- [x] Sega-GT-2002-JSRF-Jet-Set-Radio-Future #339 
- [x]  JSRF-Jet-Set-Radio-Future #339
- [x] Shenmue II
- [ ] [UEFA Champions League 2004-2005](https://xemu.app/titles/45410070#UEFA-Champions-League-2004-2005) (Loud crackling when scoring)
- [x] https://xemu.app/titles/41430014/#XGRA-Extreme-G-Racing-Association

### FMV Desync/lag.
- [x] https://xemu.app/titles/434d0047/#Second-Sight (FMV are out of sync)
- [ ] https://xemu.app/titles/54510018/#The-Punisher (FMV are out of sync)
- [ ] https://xemu.app/titles/454d0008#Bad-Boys-II (FMV are out of sync)
- [ ] https://xemu.app/titles/454d0016/#Bad-Boys-Miami-Takedown (FMV are out of sync)
- [ ] https://xemu.app/titles/41430018/#All-Star-Baseball-2004-featuring-Derek-Jeter (Lags)
- [ ] https://xemu.app/titles/56550023/#The-Hobbit-The-Prelude-to-the-Lord-of-the-Rings (Audio desyncs)

### Miscellaneous
- [ ] https://xemu.app/titles/4156002b/#Spider-Man-2 (Ingame cutscenes Audio desyncs)
- [x] Sega-GT-Online (Use multiple Voice channel sound muffled)
- [ ]https://xemu.app/titles/4143000c/#Urban-Freestyle-Soccer (Use multiple Voice channel sound muffled skateboard sound is corrupted)
- [x] https://xemu.app/titles/4947002c/#Sega-GT-2002 (Use multiple Voice channel sound muffled)
- [ ] https://xemu.app/titles/4d530021/#Crimson-Skies-High-Road-to-Revenge (Use multiple Voice channel sound muffled) (#147)
- [ ] https://xemu.app/titles/45410032/#F1-Career-Challenge (echoes)
- [ ] https://xemu.app/titles/4d530001/#Oddworld-Munch-s-Oddysee
- [ ] https://xemu.app/titles/4b4e0002/#AirForce-Delta-Storm(Missile alert sound crashes the game (NTSC-J) (#361)
- [ ] https://xemu.app/titles/4d530005/#Amped-Freestyle-Snowboarding (Skipping audio tracks crashes the game)
- [ ] https://xemu.app/titles/4b4e001a/#Silent-Scope-Complete (Not mentioned)
- [ ] http://xemu.app/titles/5345003c/#Sonic-Mega-Collection-Plus (Audio desyncs/FMV Laggy)
- [x] Gladius (Audio desyncs)
- [ ] https://xemu.app/titles/4c410013/#Star-Wars-Republic-Commando (Audio cues are broken)
- [ ] http://xemu.app/titles/4c41001a/#Star-Wars-Battlefront-II (Audio skipping) 
- [ ] https://xemu.app/titles/41430004/#Turok-Evolution (Intro has the audio cutout, voice line only play from one ear)
- [x] Teenage-Mutant-Ninja-Turtles-2-Battle-Nexus (Screeching sonud) (Didn't test but tested the 3rd game)
- [x] Teenage-Mutant-Ninja-Turtles-3-Mutant-Nightmare (Screeching sonud)
- [x] Madden-NFL-2004 (announcers voice line only play from one ear/crackling)
- [x] MVP-06-NCAA-Baseball (announcers voice line only play from one ear/crackling)
- [ ] https://xemu.app/titles/53450029/#Spikeout-Battle-Street (Sometimes messes up)
- [ ] https://xemu.app/titles/4d570029/#Mortal-Kombat-Shaolin-Monks (Audio sync issue during cutscenes)
- [ ] https://xemu.app/titles/41430010/#SX-Superstar (Not Stated)
- [x] Battlestar-Galactica (voice line only play from one ear)

 ### Surround Sound unimplemented 
[Game list not complete may add later](https://www.mobygames.com/game/attribute:474/platform:xbox/sort:title/page:1/)

### Dsp issues causing games to Assert
https://xemu.app/titles/4156000f/#Star-Wars-Obi-Wan #566
https://xemu.app/titles/4d49000c/#RPM-Tuning #332
https://xemu.app/titles/4b420007/#Top-Gear-RPM-Tuning #332
https://xemu.app/titles/54510023/#Sphinx-and-the-Cursed-Mummy #332  ?
https://xemu.app/titles/45410014/#F1-2002 #325

 ### Expected Behavior
The Audio Should work correctly

### Additional Context
Update: I Have Retested most of the games as of  0.8.96 and anything With a * has been tested recently.  
Used Real time DPS when testing  with it off some issues still occur.

**Comment by RageXbox** [comment]
Halo 2 as well for utilization crackle

**Comment by AhayriSG** [comment]
https://github.com/mborgerson/xemu/issues/531

**Comment by FlavioBSJ** [comment]
Otogi 1 has the Utilziation crackiling/Stuttering problem as well, but for some reason it only really starts being apparent around stage 5, with really bad effects at stage 6.

**Comment by MaouYumisu1** [comment]
AMF Bowling 2004 intro FMV stuttering constantly. https://youtu.be/mhTrF2u1uic

**Comment by RitschiRitsch** [comment]
I may add Painkiller Hell Wars to that list. Some sound effects are missing or on low volume (e.g. rotating sound of Painkiller weapon is missing; shotgun primary fire low volume).

**Comment by RinMaru** [comment]
https://xemu.app/titles/4d530053/#Grabbed-by-the-Ghoulies **Grabbed by the Ghoulies** also has audio issues where sound effects are very low volume to the point you cant hear anything but music
https://xemu.app/titles/54510005/#Red-Faction-II **Red Faction 2**  Has missing audio only Music plays

**Comment by Hinotoumei** [comment]
hunter the reckoning and hunter rededeemer both still have audio problems. there's no sfx. enabling dsp makes it worse.

**Comment by RinMaru** [comment]
https://xemu.app/titles/5451008b/#Nickelodeon-Tak-2-The-Staff-of-Dreams **Tak 2 and the staff of dreams** suffers from audio sounding very low quality the grunts and voice files in particular

**Comment by MaouYumisu1** [comment]
Tiger Woods PGA Tour 2006 has alot of audio stuttering ingame. https://youtu.be/QBAm_oUj0Ps
Not as bad with the rain but still there. https://xemu.app/titles/4541007e/#Tiger-Woods-PGA-Tour-06

**Comment by Finalzero2005** [comment]
https://xemu.app/titles/4d530004/#Halo-Combat-Evolved
I'm playing the german version of this game and Cortana and the Master Chief are WAY TOO QUIET. You can barely hear some during cutscenes or in-game. The Marines and Covenants on the other hand sound perfectly fine.

**Comment by michaelCaleyWhaley** [comment]
+1 still seeing sound issues in Hunter the reckoning

**Comment by hmuphilly** [comment]
Air Force Delta Storm should be considered broken on steam deck, half of the screen is missing and the first screen becomes glitchy.

**Comment by ehw** [comment]
One thing I noticed with Black Stone, the sound effects somewhat play (but are very crushed and clip a lot) with Real-time DSP processing DISABLED. If it's enabled, no sound effects play at all. Only music is unaffected.

**Comment by TheChosenOne914** [comment]
the punisher i keep getting this c++ error at random times happens when i start the xemu app or certain levels clicking on abort retry ignore all do the same either crashes xemu app forcing it to close or lock up and freeze up not responding Microsoft Visual C++ Runtime Library Assertion Failed! Program File: /hw/xbox/nv2a/pfifo.c Line: 297 Expression false for information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts (Press Retry to debug the application - jit must be enabled)

**Comment by KhenemetHeru** [comment]
Various games, but specific example: Battlestar Galactica - Cutscene videos start skipping/stuttering audio; seems to be video-related as it shows a severe dip in framerate on both audio and video in live debug window at the time, like, every other second, after about 1 minute or so of playing the cutscene. Every long cutscene video does it, regardless of rendering engine, vsync on/off and dsp on/off; shorter ones under a minute do not. This has been an issue for quite some time going back at least a year or more. Perhaps caching?

**Comment by ghost** [comment]
https://xemu.app/titles/45410035/#NCAA-Football-2004

**Comment by OrganicOstrich** [comment]
MTV Music Generator 3 Remix no longer has any audio issues

**Comment by OrganicOstrich** [comment]
Mashed: Fully Loaded has no audio issues and needs to be removed

**Comment by mirrornoir** [comment]
+1 for Call of Duty 2: Big Red One having audio issues in cut scenes only. The videos _seems_ to play at half frame rate (_Edit: Confirmed 15 fps average_) and the audio exhibits a doubling up, in which each "cached" couple second snippets of audio is repeated twice before continuing. I'd argue this may be a video decoding issue rather than pure audio.

The audio in the rest of the game is fine, despite some ~22Khz sounding sound effect samples which are most likely intended, although original console comparisons were not performed. 

Videos and audio perform as expected in the sequel by the same studio, Treyarch, in Call of Duty 3. I'll be happy to provide any additional debugging information required.

**Comment by thekovic** [comment]
[Half-Life 2](https://xemu.app/titles/45410091/#Half-Life-2) might need to be added. Many effects (for example, Combine soldier gun shots) only play in the left ear/speaker. Makes it very difficult to tell which direction you are being attacked from.

**Comment by OrganicOstrich** [comment]
Out Run Coast 2 Coast didn't have any noticeable stuttering

**Comment by KenDoStudios** [comment]
Lord Of the rings third age is not running audio completely

**Comment by Miguelkk533** [comment]
como baixa o jogo ?how to download the game

**Comment by KenDoStudios** [comment]
I'm sure if you search you can find it

**Comment by antoniodesousa** [comment]
The Punisher TQ-024 [54510018] should be removed from this list.
I just tested it in the latest build and all cutscenes FMV/real-time are in sync.

BUILD INFO
Version:      0.7.131
Branch:       master
Commit:       a8d8ef5484686ab53e67ae10363747eec7eb6729
Date:         Tue Jul 23 06:54:54 UTC 2024
SYSTEM INFO
CPU:          AMD Ryzen 9 6900HX with Radeon Graphics        
OS Platform:  Windows
OS Version:    23H2
Manufacturer: ATI Technologies Inc.
GPU Model:    AMD Radeon RX 6600M
Driver:       4.0.0 Core Profile Context 24.7.1.240711
Shader:       4.60

**Comment by ghyujkilop** [comment]
[Furious Karting](https://xemu.app/titles/4947000b/#Furious-Karting) - [When racing the audio does weird stutter/lags in audio. Also the engine audio to begin with is extremely loud.](https://youtu.be/cR8GhEHs7II)

All Sims Games: #1744 

Same with [Burnout 3: Takedown](https://xemu.app/titles/4541005b/#Burnout-3-Takedown) in [this video](https://youtu.be/_QxE3kmfHjk).

[Amped: Freestyle Snowboarding](https://xemu.app/titles/4d530005/#Amped-Freestyle-Snowboarding) - Sound effects are louder than music a fair few db's.

[TimeSplitters 2](https://xemu.app/titles/4553000a/#TimeSplitters-2) - Gun audio problems with zappy guns especially. Really loud.

**Comment by ghyujkilop** [comment]
Testing crash nitro cart on the latest version even at 4x has no issues. This is not with the experimental mode turned on.

**Comment by benjamintoledo** [comment]
Currently, audio in https://xemu.app/titles/4d530004/#Halo-Combat-Evolved works perfectly. Had played it, and no problem. Please, remove it from here.

**Comment by 0Latte** [comment]
https://xemu.app/titles/54510027/#Nickelodeon-SpongeBob-SquarePants-The-Movie has audio mixing issues where level sounds are often too loud while the music is quieter than it should be.

**Comment by jyetcv** [comment]
[Raze's Hell](https://xemu.app/titles/4d4a0011/#Raze-s-Hell) Sounds might have a larger radius or less drop off than they should.

https://github.com/user-attachments/assets/ab69504a-7e0b-44ef-b324-6f648aff3c25

[Conker Live & Reloaded](https://xemu.app/titles/4d530051/#Conker-Live-Reloaded) Early part of the music does not play during the intro.

https://github.com/user-attachments/assets/c451ca2a-be47-4617-ab1c-74f43b078cad

**Comment by RinMaru** [comment]
Grand Theft Auto San Andreas seems to have audio skip in the opening mission and CJ just wont talk when biking away

**Comment by Chase-Ehlert** [comment]
Are there any recommendations for helping to test or resolve bugs?

**Comment by Triticum0** [comment]
@Chase-Ehlert  Turn on real time dsp can help resolve some of issues. But seem quite Buggy, and can impact performance. Would need to have a side by side comparison of hw to know for sure its fully correct. But in some case improves audio. One example, some ea sport game have announcer on only one one speaker on headphones though turn dsp on fixed that specific issue. Though very case by case depending on audio engine and what xemu can't emulate correctly. Also surround sound hasn't been implemented so also could cause issues.

**Comment by Chase-Ehlert** [comment]
What about trying to contribute and fix any bugs?

**Comment by Triticum0** [comment]
Are you a programmer? Or you mean just testing?

**Comment by Chase-Ehlert** [comment]
Yes, I'm a Software Engineer. I don't have a lot of experience with C or Python but I'm curious about trying to contribute.

**Comment by Triticum0** [comment]
You have to give me a while to get some info together but audio code was based on another github repository. Not sure how much. Reading through audio code would help. Find a game you like with audio issues and debug it. A lot of games with audio issues stem from using a lot of channels and causing sub 1 fps frames. Example #579. You might want to speak with main dev @mborgerson as he worked on that part of repo before. Coldhex was also working on it recently.

FYI some of the issues on this meta maybe outdated as took some of the info from compatibility reports few years back
Edit:
I checked the depo where code located xemu/hw/xbox/mcpx/dsp/dsp.c seems the dsp code was adapted from Hatari DSP M56001 emulation https://github.com/hatari/hatari/tree/master/src/falcon. that is what the emu based dsp interpreter on.  There are quite a few issues on xqemu when the code was being worked on a lot more that I don't think was ever moved when dev migrated the emulator. may or may not be relevant but will post for thoroughness. not a dev just been tested for a few years so seem most issue or the emulator. Issues from xqemu [1.](https://github.com/xqemu/xqemu/issues/240) [2.](https://github.com/xqemu/xqemu/issues/191) [3.](https://github.com/xqemu/xqemu/issues/155)
[4.](https://github.com/JayFoxRox/xqemu/pull/22) [The rest](https://github.com/xqemu/xqemu/issues?q=is%3Aissue%20state%3Aopen%20label%3Aarea%3Aaudio%20author%3AJayFoxRox)

If you want to contribute on audio specifically you would preferably need an xbox and to learn a bit about https://github.com/XboxDev/nxdk for testing. There is a decent amount of resources on dsp above. If it hasn't already been done, probably a good place to start https://github.com/xqemu/xqemu/issues/98 also dont think code got upstreamed either from masters.

It you just want to contribute in general abaire made lot of strides trying to create some [automation tools ](https://github.com/abaire/nxdk_pgraph_tests/pull/128/commits)to allow you to create test cases for issues in-games compared to hw comparison. His repository should have a lot of useful info as well. [coldhex ](https://github.com/xemu-project/xemu/compare/master...coldhex:xemu:dev)also has some unmerged code there is no wasted work if you where going to work on the same thing by chance.

This could also be useful https://xemu.app/docs/dev/ If you want to contribute.

You can ping mborgerson on discord or github if you have any question. Also abaire can help you set up nxdk pgraph test if he not busy. No shortage of work, I also need to go back and test some of these game to see what been improved but quite hard to tell unless i have two audios to compare each other.

**Comment by Chase-Ehlert** [comment]
Wow, thanks for all of the suggestions! I'll definitely start working on this.

**Comment by Triticum0** [comment]
np, Guess I find out what you chose one a pr is opened. I only really scratched the surface many other thing I could of mentioned but I send matt a message on discord so I may or may not comment on here as reply but It doesn't really matter. Enjoy rest of your day.

**Comment by blakeplusplus** [comment]
Will +1 on Tony Hawk's American Wasteland. Sounds in general are just mixed horribly and don't seem to respect game settings unless you put it to 0. Music is fine though.
<details>
<summary>Xemu About Info</summary>

```
Version:      0.8.47
Branch:       master
Commit:       f82c6865fc27a07f52470e0a1da30151b130b4a2
Date:         Wed Apr  2 19:04:45 UTC 2025

CPU:          AMD Ryzen 7 7800X3D 8-Core Processor           
OS Platform:  Windows
OS Version:    22H2
Manufacturer: ATI Technologies Inc.
GPU Model:    AMD Radeon RX 7900 XT
Driver:       4.0.0 Core Profile Context 25.3.1.250220
Shader:       4.60

MCPX Boot ROM MD5 Hash:        d49c52a4102f6df7bcf8d0617ac475ed
Flash ROM (BIOS) MD5 Hash:     21445c6f28fca7285b0f167ea770d1e5
```

</details>

**Comment by MaxiFull10** [comment]
Hey guys im new to github so don't mind me if I post something incorrectly or where I shouldn´t, but Rallisport Challenge 2 still has audio issues but the issue has been closed. I don't know if I'm right to post this, but it happens when multiple cars are on track. Now im not the only one who has reported this but it looks like those guys have been ignored not sure if they actually were.

**Comment by Triticum0** [comment]
@jyetcv The super monkey audio is not a xemu bug but an issue with the port https://tcrf.net/Super_Monkey_Ball_Deluxe#Unused_Audio

**Comment by blakeplusplus** [comment]
https://xemu.app/titles/41510003/#Sentou-Yousei-Yukikaze-Yousei-no-Mau-Sora
Suffers from various sounds, dialogue, and music not properly playing and instead static/crackling is present. Happens in both menus and in-game.
```
Version:      0.8.72
Branch:       master
Commit:       ae12bf4318141ee216da3524ba94dacd68ad2e3f
Date:         Sat Jun 14 00:48:28 UTC 2025
CPU:          AMD Ryzen 7 7800X3D 8-Core Processor           
OS Platform:  Linux
OS Version:   Arch Linux
Manufacturer: AMD
GPU Model:    AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 20.1.6, DRM 3.63, 6.15.2-arch1-1)
Driver:       4.6 (Core Profile) Mesa 25.1.3-arch1.3
Shader:       4.60
```

**Comment by Damian21710** [comment]
Voodoo Vince has a problem with graphics constantly flickering and vanishing, including Vince himself.

**Comment by tdl76** [comment]
Simpsons hit and run has zero audio once entering gameplay. Seems to wipe out xemu audio at the same time

**Comment by MasonT8198** [comment]
@Triticum0 or @mborgerson can you pull The Incredible Hulk: Ultimate Destruction off of this issue list, this is no longer a problem.

**Comment by SOLDIER1STC** [comment]
It should be noted that as of typing this, the audio looping issue for Call of Duty 2: Big Red One thankfully only happens in the videos (such as the history channel footage shown before a mission) and not during gameplay and the in-game cutscenes.
